#ifndef CONSTANTS_MOVE_EFFECTS_H
#define CONSTANTS_MOVE_EFFECTS_H

#define MOVE_EFFECT_HIT 0
#define MOVE_EFFECT_POISON_HIT 2
#define MOVE_EFFECT_HEAL_HALF_DAMAGE_DEALT 3
#define MOVE_EFFECT_BURN_HIT 4
#define MOVE_EFFECT_FREEZE_HIT 5
#define MOVE_EFFECT_PARALYZE_HIT 6
#define MOVE_EFFECT_HALVE_DEFENSE 7
#define MOVE_EFFECT_DREAM_EATER 8
#define MOVE_EFFECT_MULTI_HIT 29
#define MOVE_EFFECT_FLINCH_HIT 31
#define MOVE_EFFECT_HEAL_HALF_MAX_HP 32
#define MOVE_EFFECT_RANDOM_PRIMARY_STATUS_HIT 36 // tri attack
#define MOVE_EFFECT_REST 37
#define MOVE_EFFECT_ONE_HIT_KO 38
#define MOVE_EFFECT_HIGH_CRITICAL 43
#define MOVE_EFFECT_RECOIL_ON_MISS 45
#define MOVE_EFFECT_ONE_QUARTER_RECOIL 48
#define MOVE_EFFECT_LOWER_ATTACK_HIT 68
#define MOVE_EFFECT_LOWER_DEFENSE_HIT 69
#define MOVE_EFFECT_LOWER_SPEED_HIT 70
#define MOVE_EFFECT_LOWER_SP_ATK_HIT 71
#define MOVE_EFFECT_LOWER_SP_DEF_HIT 72
#define MOVE_EFFECT_LOWER_ACCURACY_HIT 73
#define MOVE_EFFECT_CONFUSE_HIT 76
#define MOVE_EFFECT_POISON_MULTI_HIT 77
#define MOVE_EFFECT_COUNTER 89
#define MOVE_EFFECT_LEAVE_WITH_1_HP 101
#define MOVE_EFFECT_THAW_AND_BURN_HIT 125
#define MOVE_EFFECT_HEAL_HP_MORE_IN_SUN 132
#define MOVE_EFFECT_RAISE_ATTACK_HIT 139
#define MOVE_EFFECT_RAISE_ALL_STATS_HIT 140
#define MOVE_EFFECT_MIRROR_COAT 144
#define MOVE_EFFECT_FLINCH_DOUBLE_DAMAGE_FLY_OR_BOUNCE 146
#define MOVE_EFFECT_FLINCH_MINIMIZE_DOUBLE_HIT 150
#define MOVE_EFFECT_THUNDER 152
#define MOVE_EFFECT_SWALLOW 162
#define MOVE_EFFECT_WISH 179
#define MOVE_EFFECT_REMOVE_SCREENS 186
#define MOVE_EFFECT_SECRET_POWER 197
#define MOVE_EFFECT_RECOIL_HIT 198
#define MOVE_EFFECT_HIGH_CRITICAL_BURN_HIT 200
#define MOVE_EFFECT_FLINCH_POISON_HIT 202
#define MOVE_EFFECT_HIGH_CRITICAL_POISON_HIT 209
#define MOVE_EFFECT_ROOST 214
#define MOVE_EFFECT_HEALING_WISH 220
#define MOVE_EFFECT_METAL_BURST 227
#define MOVE_EFFECT_RECOIL_BURN_HIT 253
#define MOVE_EFFECT_BLIZZARD 260
#define MOVE_EFFECT_RECOIL_PARALYZE_HIT 262
#define MOVE_EFFECT_CHATTER 267
#define MOVE_EFFECT_ONE_HALF_RECOIL 269
#define MOVE_EFFECT_LUNAR_DANCE 270
#define MOVE_EFFECT_LOWER_SP_DEF_2_HIT 271
#define MOVE_EFFECT_FLINCH_BURN_HIT 273
#define MOVE_EFFECT_FLINCH_FREEZE_HIT 274
#define MOVE_EFFECT_FLINCH_PARALYZE_HIT 275
#define MOVE_EFFECT_RAISE_SP_ATK_HIT 276

// new move effects:
#define MOVE_EFFECT_DOUBLE_DAMAGE_POISON 280
#define MOVE_EFFECT_GUARANTEED_CRIT 282
#define MOVE_EFFECT_RAISE_SPEED_HIT 285

#define MOVE_EFFECT_PSYSHOCK 293
#define MOVE_EFFECT_FOUL_PLAY 294
#define MOVE_EFFECT_SACRED_SWORD 295
#define MOVE_EFFECT_BODY_PRESS 296
#define MOVE_EFFECT_FREEZE_DRY 299
#define MOVE_EFFECT_STONE_AXE 305
#define MOVE_EFFECT_BARB_BARRAGE 306
#define MOVE_EFFECT_ESPER_WING 308
#define MOVE_EFFECT_FREEZE_DRY_NO_FREEZE 309

#endif
